#include "../native/clang-format-options-update/Format.h"
#include "../native/clang-format-options-update/update.h"
#include <catch2/catch_test_macros.hpp>
#include <filesystem>
#include <frozen/bits/hash_string.h>
#include <frozen/unordered_map.h>
#include <frozen/unordered_set.h>
#include <fstream>
#include <iostream>
#include <magic_enum/magic_enum.hpp>
#include <sstream>
#include <string>

namespace frozen {
template <> struct elsa<std::string_view> {
  constexpr std::size_t operator()(std::string_view value) const {
    return hash_string(value);
  }
  constexpr std::size_t operator()(std::string_view value,
                                   std::size_t seed) const {
    return hash_string(value, seed);
  }
};
} // namespace frozen

namespace {

std::ostream &operator<<(std::ostream &os, clang_vx::Version v) {
  if (auto name = magic_enum::enum_name(v); !name.empty()) {
    os << name;
  } else {
    os << "Unknown";
  }
  return os;
}

std::ostream &operator<<(std::ostream &os,
                         const std::vector<clang_vx::Version> &versions) {
  os << "[";
  bool first = true;
  for (const auto &v : versions) {
    if (!first) {
      os << ", ";
    }
    os << v;
    first = false;
  }
  os << "]";
  return os;
}

constexpr frozen::unordered_set<std::string_view, 9> styles{
    "chromium",  "clang-format", "gnu",  "google", "llvm",
    "microsoft", "mozilla",      "none", "webkit"};

std::map<std::string_view, std::vector<clang_vx::Version>> compatibilities{
    {"chromium-3_4.cfg",
     {clang_vx::Version::V3_4, clang_vx::Version::V3_5, clang_vx::Version::V3_6,
      clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4,   clang_vx::Version::V5,   clang_vx::Version::V6,
      clang_vx::Version::V7,   clang_vx::Version::V8,   clang_vx::Version::V9,
      clang_vx::Version::V10,  clang_vx::Version::V11,  clang_vx::Version::V12,
      clang_vx::Version::V13,  clang_vx::Version::V14,  clang_vx::Version::V15,
      clang_vx::Version::V16,  clang_vx::Version::V17,  clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                          clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                          clang_vx::Version::V3_9, clang_vx::Version::V4,
                          clang_vx::Version::V5,   clang_vx::Version::V6,
                          clang_vx::Version::V7,   clang_vx::Version::V8,
                          clang_vx::Version::V9,   clang_vx::Version::V10,
                          clang_vx::Version::V11,  clang_vx::Version::V12,
                          clang_vx::Version::V13,  clang_vx::Version::V14,
                          clang_vx::Version::V15,  clang_vx::Version::V16,
                          clang_vx::Version::V17,  clang_vx::Version::V18,
                          clang_vx::Version::V19}},
    {"chromium-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"chromium-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-6.cfg", {clang_vx::Version::V6}},
    {"chromium-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"chromium-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"chromium-19.cfg", {clang_vx::Version::V19}},
    {"clang-format-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"clang-format-19.cfg", {clang_vx::Version::V19}},
    {"gnu-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                     clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                     clang_vx::Version::V3_9, clang_vx::Version::V4,
                     clang_vx::Version::V5,   clang_vx::Version::V6,
                     clang_vx::Version::V7,   clang_vx::Version::V8,
                     clang_vx::Version::V9,   clang_vx::Version::V10,
                     clang_vx::Version::V11,  clang_vx::Version::V12,
                     clang_vx::Version::V13,  clang_vx::Version::V14,
                     clang_vx::Version::V15,  clang_vx::Version::V16,
                     clang_vx::Version::V17,  clang_vx::Version::V18,
                     clang_vx::Version::V19}},
    {"gnu-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"gnu-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"gnu-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"gnu-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-6.cfg", {clang_vx::Version::V6}},
    {"gnu-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"gnu-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"gnu-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"gnu-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"gnu-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"gnu-19.cfg", {clang_vx::Version::V19}},
    {"google-3_4.cfg",
     {clang_vx::Version::V3_4, clang_vx::Version::V3_5, clang_vx::Version::V3_6,
      clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4,   clang_vx::Version::V5,   clang_vx::Version::V6,
      clang_vx::Version::V7,   clang_vx::Version::V8,   clang_vx::Version::V9,
      clang_vx::Version::V10,  clang_vx::Version::V11,  clang_vx::Version::V12,
      clang_vx::Version::V13,  clang_vx::Version::V14,  clang_vx::Version::V15,
      clang_vx::Version::V16,  clang_vx::Version::V17,  clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                        clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                        clang_vx::Version::V3_9, clang_vx::Version::V4,
                        clang_vx::Version::V5,   clang_vx::Version::V6,
                        clang_vx::Version::V7,   clang_vx::Version::V8,
                        clang_vx::Version::V9,   clang_vx::Version::V10,
                        clang_vx::Version::V11,  clang_vx::Version::V12,
                        clang_vx::Version::V13,  clang_vx::Version::V14,
                        clang_vx::Version::V15,  clang_vx::Version::V16,
                        clang_vx::Version::V17,  clang_vx::Version::V18,
                        clang_vx::Version::V19}},
    {"google-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"google-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-6.cfg", {clang_vx::Version::V6}},
    {"google-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"google-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"google-19.cfg", {clang_vx::Version::V19}},
    {"llvm-3_4.cfg",
     {clang_vx::Version::V3_4, clang_vx::Version::V3_5, clang_vx::Version::V3_6,
      clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4,   clang_vx::Version::V5,   clang_vx::Version::V6,
      clang_vx::Version::V7,   clang_vx::Version::V8,   clang_vx::Version::V9,
      clang_vx::Version::V10,  clang_vx::Version::V11,  clang_vx::Version::V12,
      clang_vx::Version::V13,  clang_vx::Version::V14,  clang_vx::Version::V15,
      clang_vx::Version::V16,  clang_vx::Version::V17,  clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                      clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                      clang_vx::Version::V3_9, clang_vx::Version::V4,
                      clang_vx::Version::V5,   clang_vx::Version::V6,
                      clang_vx::Version::V7,   clang_vx::Version::V8,
                      clang_vx::Version::V9,   clang_vx::Version::V10,
                      clang_vx::Version::V11,  clang_vx::Version::V12,
                      clang_vx::Version::V13,  clang_vx::Version::V14,
                      clang_vx::Version::V15,  clang_vx::Version::V16,
                      clang_vx::Version::V17,  clang_vx::Version::V18,
                      clang_vx::Version::V19}},
    {"llvm-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"llvm-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-6.cfg", {clang_vx::Version::V6}},
    {"llvm-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"llvm-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"llvm-19.cfg", {clang_vx::Version::V19}},
    {"microsoft-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"microsoft-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"microsoft-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"microsoft-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"microsoft-19.cfg", {clang_vx::Version::V19}},
    {"mozilla-3_4.cfg",
     {clang_vx::Version::V3_4, clang_vx::Version::V3_5, clang_vx::Version::V3_6,
      clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4,   clang_vx::Version::V5,   clang_vx::Version::V6,
      clang_vx::Version::V7,   clang_vx::Version::V8,   clang_vx::Version::V9,
      clang_vx::Version::V10,  clang_vx::Version::V11,  clang_vx::Version::V12,
      clang_vx::Version::V13,  clang_vx::Version::V14,  clang_vx::Version::V15,
      clang_vx::Version::V16,  clang_vx::Version::V17,  clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                         clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                         clang_vx::Version::V3_9, clang_vx::Version::V4,
                         clang_vx::Version::V5,   clang_vx::Version::V6,
                         clang_vx::Version::V7,   clang_vx::Version::V8,
                         clang_vx::Version::V9,   clang_vx::Version::V10,
                         clang_vx::Version::V11,  clang_vx::Version::V12,
                         clang_vx::Version::V13,  clang_vx::Version::V14,
                         clang_vx::Version::V15,  clang_vx::Version::V16,
                         clang_vx::Version::V17,  clang_vx::Version::V18,
                         clang_vx::Version::V19}},
    {"mozilla-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"mozilla-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-6.cfg", {clang_vx::Version::V6}},
    {"mozilla-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"mozilla-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"mozilla-19.cfg", {clang_vx::Version::V19}},
    {"none-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                      clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                      clang_vx::Version::V3_9, clang_vx::Version::V4,
                      clang_vx::Version::V5,   clang_vx::Version::V6,
                      clang_vx::Version::V7,   clang_vx::Version::V8,
                      clang_vx::Version::V9,   clang_vx::Version::V10,
                      clang_vx::Version::V11,  clang_vx::Version::V12,
                      clang_vx::Version::V13,  clang_vx::Version::V14,
                      clang_vx::Version::V15,  clang_vx::Version::V16,
                      clang_vx::Version::V17,  clang_vx::Version::V18,
                      clang_vx::Version::V19}},
    {"none-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"none-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"none-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"none-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-6.cfg", {clang_vx::Version::V6}},
    {"none-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"none-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"none-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"none-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"none-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"none-19.cfg", {clang_vx::Version::V19}},
    {"webkit-3_4.cfg",
     {clang_vx::Version::V3_4, clang_vx::Version::V3_5, clang_vx::Version::V3_6,
      clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4,   clang_vx::Version::V5,   clang_vx::Version::V6,
      clang_vx::Version::V7,   clang_vx::Version::V8,   clang_vx::Version::V9,
      clang_vx::Version::V10,  clang_vx::Version::V11,  clang_vx::Version::V12,
      clang_vx::Version::V13,  clang_vx::Version::V14,  clang_vx::Version::V15,
      clang_vx::Version::V16,  clang_vx::Version::V17,  clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-3_5.cfg", {clang_vx::Version::V3_5, clang_vx::Version::V3_6,
                        clang_vx::Version::V3_7, clang_vx::Version::V3_8,
                        clang_vx::Version::V3_9, clang_vx::Version::V4,
                        clang_vx::Version::V5,   clang_vx::Version::V6,
                        clang_vx::Version::V7,   clang_vx::Version::V8,
                        clang_vx::Version::V9,   clang_vx::Version::V10,
                        clang_vx::Version::V11,  clang_vx::Version::V12,
                        clang_vx::Version::V13,  clang_vx::Version::V14,
                        clang_vx::Version::V15,  clang_vx::Version::V16,
                        clang_vx::Version::V17,  clang_vx::Version::V18,
                        clang_vx::Version::V19}},
    {"webkit-3_6.cfg",
     {clang_vx::Version::V3_6, clang_vx::Version::V3_7, clang_vx::Version::V3_8,
      clang_vx::Version::V3_9, clang_vx::Version::V4,   clang_vx::Version::V5,
      clang_vx::Version::V6,   clang_vx::Version::V7,   clang_vx::Version::V8,
      clang_vx::Version::V9,   clang_vx::Version::V10,  clang_vx::Version::V11,
      clang_vx::Version::V12,  clang_vx::Version::V13,  clang_vx::Version::V14,
      clang_vx::Version::V15,  clang_vx::Version::V16,  clang_vx::Version::V17,
      clang_vx::Version::V18,  clang_vx::Version::V19}},
    {"webkit-3_7.cfg",
     {clang_vx::Version::V3_7, clang_vx::Version::V3_8, clang_vx::Version::V3_9,
      clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-3_8.cfg",
     {clang_vx::Version::V3_8, clang_vx::Version::V3_9, clang_vx::Version::V4,
      clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-3_9.cfg",
     {clang_vx::Version::V3_9, clang_vx::Version::V4, clang_vx::Version::V5,
      clang_vx::Version::V6, clang_vx::Version::V7, clang_vx::Version::V8,
      clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-4.cfg",
     {clang_vx::Version::V4, clang_vx::Version::V5, clang_vx::Version::V6,
      clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-5.cfg",
     {clang_vx::Version::V5, clang_vx::Version::V6, clang_vx::Version::V7,
      clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-6.cfg", {clang_vx::Version::V6}},
    {"webkit-7.cfg",
     {clang_vx::Version::V7, clang_vx::Version::V8, clang_vx::Version::V9,
      clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-8.cfg",
     {clang_vx::Version::V8, clang_vx::Version::V9, clang_vx::Version::V10,
      clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-9.cfg",
     {clang_vx::Version::V9, clang_vx::Version::V10, clang_vx::Version::V11,
      clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-10.cfg",
     {clang_vx::Version::V10, clang_vx::Version::V11, clang_vx::Version::V12,
      clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-11.cfg",
     {clang_vx::Version::V11, clang_vx::Version::V12, clang_vx::Version::V13,
      clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-12.cfg",
     {clang_vx::Version::V12, clang_vx::Version::V13, clang_vx::Version::V14,
      clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-13.cfg",
     {clang_vx::Version::V13, clang_vx::Version::V14, clang_vx::Version::V15,
      clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-14.cfg",
     {clang_vx::Version::V14, clang_vx::Version::V15, clang_vx::Version::V16,
      clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-15.cfg",
     {clang_vx::Version::V15, clang_vx::Version::V16, clang_vx::Version::V17,
      clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-16.cfg",
     {clang_vx::Version::V16, clang_vx::Version::V17, clang_vx::Version::V18,
      clang_vx::Version::V19}},
    {"webkit-17.cfg",
     {clang_vx::Version::V17, clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-18.cfg", {clang_vx::Version::V18, clang_vx::Version::V19}},
    {"webkit-19.cfg", {clang_vx::Version::V19}}};

} // namespace

TEST_CASE("getCompatibleVersion", "[clang-format-options-update]") {
  for (std::string_view style : styles) {
    for (clang_vx::Version version :
         magic_enum::enum_values<clang_vx::Version>()) {
      std::string filename =
          std::string{style} + "-" +
          std::string{magic_enum::enum_name(version).substr(1)} + ".cfg";
      if (std::filesystem::exists(filename)) {
        std::ifstream myfile;
        myfile.open(filename);
        std::string myline;
        std::stringstream ss;
        REQUIRE(myfile.is_open());
        while (myfile) {
          std::getline(myfile, myline);
          ss << myline << '\n';
        }
        std::vector<clang_vx::Version> compatible_versions =
            clang_vx::getCompatibleVersion(ss.str());
        const std::vector<clang_vx::Version> &result_expected =
            compatibilities.at(filename);
        REQUIRE(result_expected == compatible_versions);
      }
    }
  }
}

TEST_CASE("updateEnum", "[clang-format-options-update]") {
  {
    clang_v3_3::FormatStyle style3_3_old = clang_v3_3::getGoogleStyle();
    clang_v3_4::FormatStyle style3_4_new;
    clang_update_v3_4::update<clang_vx::Update::UPGRADE>(
        style3_3_old, style3_4_new, "google");

    clang_v3_4::FormatStyle style3_4_old = clang_v3_4::getGoogleStyle();
    clang_v3_3::FormatStyle style3_3_new;
    clang_update_v3_4::update<clang_vx::Update::DOWNGRADE>(
        style3_3_new, style3_4_old, "google");

    REQUIRE(style3_3_old == style3_3_new);
    REQUIRE(style3_4_old == style3_4_new);
  }
}
